### PR TITLE
Added delayed shard allocation timeout setting (introduced in ES 1.7.0)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by kamaradclimber** [comment]
-1 see f5ea7c2fd83a842da9436e4bb61e32c31cb80e31 (this commit is the reason we have the fork)

**Comment by brugidou** [comment]
Should we keep this repo forever? It seems to be a divergent fork...

**Comment by kamaradclimber** [comment]
It is and I discussed with @vvanholl today what shoudl be done to use the upstream repo

**Comment by brugidou** [comment]
So would it make sense that I move this to criteo-forks or not? Criteo-forks are for temporary forks.

**Comment by kamaradclimber** [comment]
Yes, please inform sre-storage when you've done it (even if github probably adds a redirection)

**Pull request closed without merging**
